### PR TITLE
Bronze snapshot 4.1.0

### PR DESCRIPTION
**Pull request by cmhodgson**
I believe this PR is a mess because I had to rebase due to the delete that was done on the main repo. If you can tell me what I need to do to clean it up I will. Otherwise, the changes are what is required for the bronze snapshot delivery.

### CODE REVIEW

**Comment by dkelsey** [comment]
My Comments:
* There are too many changes at once
* There are Lucene additions - I thought that was being abandoned?
* I don't see any tickets associated with all the changes.
* I saw that profiles were removed from a pom.  I know the build uses profiles.  I not aware that this was asked for.

**Comment by cmhodgson** [comment]
- your deletion caused my entire repo to become out of sync, that is why this is such a mess, I don't know how to clean it up, I don't think it is worth trying to figure it out at this time. Yes, smaller commits could help with this problem and I will work on that going forward
- The work I did with Lucene may have future uses, I didn't want to throw that out entirely
- all of the tickets tagged for bronze release are what is associated with these changes; we are not working on a 1-PR-to-1-ticket basis at this time
- the build doesn't use profiles anymore - the profiles previously embedded the deliv/test/prod-specific config variable values into the built war files, we now use environment variables instead which is more flexible - the profiles were a relic from over a version ago.

**Comment by dkelsey** [comment]
* Yes we had to re-write the history of the repo to remove exposed PI data.   Hence the mess.
* I see how it would be difficult, sort of, to associated tickets to this large PR.  If I can't understand what all the changes are for, I should not accept them.   
* I wasn't aware that we were getting rid of the profiles.   I now have to change our build to get it to work again.  minor but unexpected work.

**Comment by cmhodgson** [comment]
Sorry. The profiles weren't actually doing anything. Was just cleaning house.

**Comment by mraross** [comment]
This pull request covers all issues labelled with [bronze snapshot](https://github.com/bcgov/ols-geocoder/labels/bronze%20snapshot)

**Comment by dkelsey** [comment]
Chris, talking with Michael.... I recognized we did discuss this and that we came to an agreement about bundling large change sets in PRs due to the challenges with testing.    I get it.  I also get this was large due to the "history change" issue.   Michael added a comment which includes a link to the relevant issues.  This helps, at least, to understand what is in the PR.

**Pull request merged**
