### PR TITLE
fixed SiteLoaderPrep to output Y instead of true for is_primary

### PR DESCRIPTION
**Pull request by cmhodgson**

### CODE REVIEW

**Comment by cmhodgson** [comment]
This fix will allow future runs of the data prep - specifically SiteLoaderPrep - to output the expected "Y" instead of "true" for is_primary attribute of sites - this fixes the issue with sites/within not returning any address information.

**Comment by cmhodgson** [comment]
This issue was identified by testing for ticket: https://dpdd.atlassian.net/browse/LOC-4468
and is required in order to complete ticket: https://dpdd.atlassian.net/browse/LOC-5029

**Review by 3rdmike — APPROVED** [review]
Looks good to me

**Comment by BK01** [comment]
Validated in geocodertst.api.gov.bc.ca on Jan 11, 2024 using Oct 2023 data with previous test cases.

**Pull request merged**
