### PR TITLE
SiteLoaderPrep & SID2PID conversion from FME

### PR DESCRIPTION
**Pull request by cmhodgson**

### CODE REVIEW

**Review by bolyachevets — COMMENTED** [review]
1. Should we not include a target for SiteLoaderPrep executable in ols-geocoder-process/pom.xml (i.e., similar to line 34 <argument>ca.bc.gov.ols.rangebuilder.RangeBuilder</argument>)

2. Here is a blurb from the instructions for sid2pid step:

```
Confirm the output files were created, and review:
* \\data.bcgov\data_staging_dbc\BGEO\DATA_PREP\Staging 
    * sid2pid.csv
    * rejected_sid2pid (shapefile) - NOTE: not always, only in cases where there are rejected points
        * determine why there are rejected sites, and troubleshoot as necessary.
```
It seems that rejected_sid2pid is not created in the Java code

3. Similarly loader prep instructions list the following files:
```
Confirm the output files were generated, and review:
 \\data.bcgov\data_staging_dbc\BGEO\DATA_PREP\Staging
rejected_geocode_Hybrid (shapefile)
QA this output dataset for any rejected sites:
Compare row count or file size to previous data prep version
For any areas with suspiciously large clusters of rejected site points, review the REASON field to determine why the points were rejected. The REASON may give you an indication of what is wrong with the source data.
sid2jurol.csv
site_Hybrid.tsv
```
Not sure what rejected_geocode_Hybrid, sid2jurol.csv iare used for, do we need these files?

**Comment by cmhodgson** [comment]
1. Yes, you are correct, we should add a maven target to run the SiteLoaderPrep .
2. The sid2pid process has been integrated into the SiteLoaderPrep - as a result, any reject output that would have gone into "rejected_sid2pid" is now output with the siteLoaderPrep error outputs, in "site_loader_prep_log.csv" This file takes the place of rejected_geocode_Hybrid and rejected_sid2pid.

**Comment by bolyachevets** [comment]
> 2 & 3. The sid2pid process has been integrated into the SiteLoaderPrep - as a result, any reject output that would have gone into "rejected_sid2pid" is now output with the siteLoaderPrep error outputs, in "site_loader_prep_log.csv" This file takes the place of rejected_geocode_Hybrid and rejected_sid2pid. This also means that the intermediate file sid2jurol is not necessary.

Let me get this straight in terms of sequencing and inputs/outputs:

So, we need to build  SiteLoaderPrep, then run it standalone while supplying site_ITN_anchor_points.tsv file as input, which should produce site_Hybrid.tsv

Then we build RangeBuilder and run it standalone. What are the inputs at this stage? (since previously we had to provide VBC_PID_EXTRACT_<DATE>.csv to sid2pid stage). What are the outputs here?

**Comment by cmhodgson** [comment]
The VBC_PID_EXTRACT is now an input to the SiteLoaderPrep. It now outputs the sid2pid.csv, which is an input to the RangeBuilder. 

The inputs and outputs of the RangeBuilder are unchanged - the inputs are:
site_Hybrid.tsv
sid2pid.csv
street_load_*.json

And the outputs are:
street_load_street_segments_geocoder.json
site_Hybrid_geocoder.tsv

The SiteLoaderPrep code has all the input and output files identified near the top of the file as constants:
https://github.com/bcgov/ols-geocoder/pull/274/commits/5c931ecf4f1ef38b41cb6464a75e758ccaec04a0#diff-aa7cc03def69129ff6a195b995f64b99f2235d134ab36b56bc695d862973aa95L72

And I have done the same with the StreetPrep process that I am converting now. However the RangeBuilder shares its file reading code with the geocoder runtime and so the file names are hidden deeper.

**Comment by bolyachevets** [comment]
> 

Are we then hardcode the input file name:

private static final String VBC_PID_FILE = "VBC_PID_EXTRACT_20200801.csv";

According to my neophyte understanding of the previous instructions the file is passed to the FME script with a manually updated date:

VBC_PID_EXTRACT_<DATE>.csv

**Comment by brad-sparks-gov-bc-ca** [comment]
> > 
> 
> Are we then hardcoding the input file name:
> 
> private static final String VBC_PID_FILE = "VBC_PID_EXTRACT_20200801.csv";
> 
> According to my neophyte understanding of the previous instructions the file is passed to the FME script with a manually updated date:
> 
> VBC_PID_EXTRACT_ < DATE > .csv


Suggestion: I think we could hardcode the filename as VBC_PID_EXTRACT.csv with the _DATE removed
(and I could update our data-prep readme instructions to rename the file after it has been downloaded from the source)

**Comment by cmhodgson** [comment]
I agree Brad, I think this is the best approach as we do not include dates in any other filenames.

**Comment by bolyachevets** [comment]
I tried running "mvn clean install" against the ols-geocoder-process/pom.xml
The compilation fails with either jdk11 (on the server) and jdk14 (on my machine).
Here is the jenkins job: https://cis.apps.gov.bc.ca/int/job/ols/job/DataIntegration-SiteLoaderPrep/
The green job is for building dev branch
The red job is for running this PR
Chris let me know if you cannot access it (I did add you as collaborator).
Short snippet from the failing output:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /apps/jenkins/home/workspace/ols/DataIntegration-SiteLoaderPrep/ols-geocoder-process/src/main/java/ca/bc/gov/siteloaderprep/OutputSite.java:[52,30] cannot find symbol
  symbol:   method getUuid(java.lang.String)
  location: variable rr of type ca.bc.gov.ols.rowreader.RowReader
[ERROR] /apps/jenkins/home/workspace/ols/DataIntegration-SiteLoaderPrep/ols-geocoder-process/src/main/java/ca/bc/gov/siteloaderprep/OutputSite.java:[65,51] cannot find symbol
  symbol:   method getBoolean(java.lang.String)
  location: variable rr of type ca.bc.gov.ols.rowreader.RowReader
[ERROR] /apps/jenkins/home/workspace/ols/DataIntegration-SiteLoaderPrep/ols-geocoder-process/src/main/java/ca/bc/gov/siteloaderprep/SiteLoaderPrep.java:[215,31] incompatible types: try-with-resources not applicable to variable type
...
```

**Comment by cmhodgson** [comment]
It seems that I made an error and did not include the latest changes to the ols-util that are required for the SiteLoaderPrep in the most recently committed version of ols-util. At this point I am nearly done the StreetPrep process, which includes further updates to the ols-util. I think it makes the most sense to wait another day or two, and I will submit a new PR for ols-util, and for ols-geocoder, including all of the changes in this PR as well as the StreetPrep process, as well as the changes we've already discussed to this PR.

**Pull request closed without merging**
